# Numpy #

In [33]:
import numpy as np #importing the numpy library#

### 1.)Basics of Numpy ###

In [34]:
a=np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [35]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [36]:
#To get the dimension of the array#
a.ndim

1

In [37]:
# To get the shape
b.shape

(2, 3)

In [38]:
# Get type
a.dtype

dtype('int32')

In [39]:
# Get size
a.itemsize

4

In [40]:
# Get total size
a.nbytes

12

In [41]:
# Get number of elements
a.size

3

### 1.) Accessing/ Changing specific elements,rows,coloumns etc ###

In [42]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [43]:
# Getting a specific element [row,column]

a[1,5]

13

In [44]:
# To get a specific row #

a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [45]:
# To get a specific column #

a[:,2]

array([ 3, 10])

In [46]:
# Using start index , end index and step #

a[0,1:-1:2]

array([2, 4, 6])

In [47]:
a[1,5]
a[:,2]=[1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 13 14]]


In [48]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [49]:
# Get specific element (work outside in)
b[0,1,1]

4

### 2.) Initializing Different Types of Arrays ###

In [50]:
# To print a matrix of 0s #
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [51]:
# To print a matrix of 1s

np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [52]:
# To print a matrix of any other number

np.full((2,2),50)

array([[50, 50],
       [50, 50]])

In [53]:
# Random Decimal Values

np.random.rand(4,2)

array([[0.51359358, 0.46933909],
       [0.34688603, 0.17693247],
       [0.19206008, 0.63415897],
       [0.37144964, 0.24441234]])

In [54]:
# Random Integer values #

np.random.randint(-4,8, size=(3,3))

array([[ 0,  2,  2],
       [ 6, -1,  2],
       [-2,  0,  0]])

In [55]:
#Identity Matrix #
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [56]:
# To repeat elements an array #

arr=np.array([1,2,3])
r1=np.repeat(arr,3,axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [57]:
# WHILE COPYING ARRAYS #

a=np.array([1,2,3,4,5])
b=a.copy()
b[0]=100
print(a)
print(b)

[1 2 3 4 5]
[100   2   3   4   5]


### 3.) Mathematics Functions of Numpy ###

In [58]:
a = np.array([1,2,3,4])
print(a)


[1 2 3 4]


In [59]:
a + 2

array([3, 4, 5, 6])

In [60]:
a - 2

array([-1,  0,  1,  2])

In [61]:
a * 2

array([2, 4, 6, 8])

In [62]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [63]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [64]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [65]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

### 4.)Linear Algebra ###

In [66]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)


[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [68]:
c=np.identity(3)
np.linalg.det(c)

1.0

### 5.) Statistics ###

In [69]:
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
np.min(stats)

1

In [71]:
np.max(stats, axis =1)

array([3, 6])

In [72]:
np.sum(stats, axis = 0)

array([5, 7, 9])

### 6.)Stacking Arrays ###

In [73]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])


In [76]:
# Vertically Stacking Arrays #

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [75]:
# Horizontally stacking arrays #

np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])